#!/usr/bin/env python3
"""automation-log/log_run.py — central run-logger for ngernduangold routines.

ทุก routine เรียกตอนจบรอบ → บันทึก proof-of-execution ลง GitHub ให้ Cowork เห็น
(ไฟล์อยู่ repo root → Netlify publish=site/ จึง **ไม่ขึ้นเว็บ public**, เห็นเฉพาะบน GitHub).

⚠️ repo เป็น public → ห้ามใส่ข้อมูลอ่อนไหว (ยอดรายได้/PII/token). ใส่ได้แค่ status/count/permalink สาธารณะ.

CLI:
  python automation-log/log_run.py --routine delivery-heartbeat --status ok \
     --summary "FB+IG live" --metrics '{"fb":"live","ig":"live"}'
import:
  from log_run import log_run; log_run("queue-keeper","ok","เติม 6 โพสต์",{"added":6})
"""
import json, os, sys, argparse, datetime

HERE = os.path.dirname(os.path.abspath(__file__))

def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).astimezone().isoformat(timespec="seconds")

def log_run(routine, status, summary="", metrics=None, ts=None):
    ts = ts or _now_iso()
    entry = {"ts": ts, "routine": routine, "status": status,
             "summary": summary, "metrics": metrics or {}}
    jpath = os.path.join(HERE, ts[:7] + ".jsonl")          # e.g. 2026-06.jsonl
    with open(jpath, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    rebuild_latest()
    return entry

def rebuild_latest():
    latest = {}
    for fn in sorted(os.listdir(HERE)):
        if fn.endswith(".jsonl"):
            for line in open(os.path.join(HERE, fn), encoding="utf-8"):
                line = line.strip()
                if not line:
                    continue
                try:
                    e = json.loads(line)
                except Exception:
                    continue
                latest[e["routine"]] = e          # keep last per routine
    rows = sorted(latest.values(), key=lambda e: e["routine"])
    md = ["# ngernduangold — Automation last-run (auto-generated by log_run.py)",
          "",
          "_อัปเดต: " + _now_iso() + " · config ≠ delivered — ตารางนี้ = หลักฐาน routine fire จริง_",
          "",
          "| routine | last-run | status | summary |",
          "|---|---|---|---|"]
    for e in rows:
        md.append("| {routine} | {ts} | {status} | {summary} |".format(
            routine=e["routine"], ts=e["ts"], status=e["status"], summary=e.get("summary", "")))
    md.append("")
    with open(os.path.join(HERE, "latest.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md) + "\n")

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--routine", required=True)
    ap.add_argument("--status", required=True, help="ok | fail | partial | registered")
    ap.add_argument("--summary", default="")
    ap.add_argument("--metrics", default="{}")
    a = ap.parse_args()
    try:
        m = json.loads(a.metrics)
    except Exception:
        m = {"raw": a.metrics}
    print(json.dumps(log_run(a.routine, a.status, a.summary, m), ensure_ascii=False))
